name: typesetting_prototype
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  pdf: ^3.11.3
  dart_eval:
  path: ^1.8.0
  http:
  web:

dev_dependencies:
  dart_style:
  code_builder:
  collection: ^1.18.0
  analyzer:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.15
  build_test: ^2.2.3
  build_web_compilers: ^4.1.5
