name: deploy web

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show all files in repository
        run: ls -RF

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.8.1

      - name: Install dependencies
        run: dart pub get

      - name: Activate webdev
        run: dart pub global activate webdev

      - name: Build web app
        run: webdev build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
