name: deploy web

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.8.1

      - name: Install dependencies
        run: dart pub get

      - name: Activate webdev
        run: dart pub global activate webdev

      - name: Build web app
        id: build
        run: dart run build_runner build --delete-conflicting-outputs -o web:build
        continue-on-error: true

      - name: Check build status and debug on failure
        run: |
          ls -RF build
          echo "Exiting with error to stop the workflow."
          exit 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
